### ISSUE TITLE
Remote Debugging

### ISSUE THREAD

**Issue by EmadRadwan** [danwatford/ofbiz-docker#1]
Hello,

What modifications need to be done to allow remote debugging in a tool like IntelliJ

Regards,
Emad

**Comment by danwatford** [comment]
Hi Emad,

The following is copied from our discussion on the OFBiz User mailing list:

I've not tested this today, but try replacing the docker-compose.yml file with something similar to :

```
version: '3.2'

services:
  activate:
    image: ofbiz:latest
    command: ./gradlew "ofbizDebug --load-data dir=local-config" ofbiz
    volumes:
      - type: bind
        source: ./local-config
        target: /ofbiz/local-config
    ports:
      - 8443:8443
      - 5005:5005
```

In the above docker-compose.yml file, the command now runs the ofbizDebug gradle task rather than ofbiz.

Running the ofbizDebug task sets debug=true on the underlying gradle JavaExec task used to run ofbiz. When debug=true the JVM is launched in the suspended debug state, listening on port 5005 for a debugger to connect..

In the above docker-compose.yml file, port 5005 has been exposed meaning your debugger should be able to connect to the ofbiz JVM.

Please let us know if the above works for you.
